import os
from datetime import datetime

vault = os.path.expanduser("~/GTM 2nd Brain")
research_dir = os.path.join(vault, "30_Resources/Research")
os.makedirs(research_dir, exist_ok=True)

date_str = datetime.now().strftime("%Y-%m-%d")
file_path = os.path.join(research_dir, f"GTM_Research_{date_str}.md")

content = f"""---
type: resource
category: research
tags:
  - gtm
  - revops
  - research
date: {date_str}
status: automated
---

# GTM & RevOps Automated Intelligence Digest - {date_str}

## Key Focus Areas
- **PLG & PQL Routing:** Industry shifts in product-qualified lead thresholds.
- **Attribution & Data Pipeline:** Modern warehousing patterns for hybrid GTM models.

## Automated Summary
* This note was generated by your automated background research engine.
* Connect this file to external RSS feeds or LLM API endpoints to populate live market insights.
"""

with open(file_path, "w") as f:
    f.write(content)

print(f"Created research note at {file_path}")
